import React, { useState } from 'react';
import { useDispatch } from 'src/context';
import { actionsCreator } from 'src/context/user/actions';
import { IIvms101Message } from '../../../interfaces/IIvms101Message';
import buildHandler from '../../../utils/buildDinamicsStates';

const TravelRule: React.FC = () => {
	const dispatch = useDispatch();

	const emptyMessage: IIvms101Message = {
	firstName: '',
	lastName: '',
	streetName: '',
	buildingNumber: '',
	country: ''
	};
	const [firstName, setFirstName] = useState<string>('');
	const [lastName, setLastName] = useState<string>('');
	const [streetName, setStreetName] = useState<string>('');
	const [buildingNumber, setBuildingNumber] = useState<string>('');
	const [country, setCountry] = useState<string>('');
	const [passportButton, setPassportButton] = useState<string>('button primary');
	const [savePassport, setSavePassport] = useState<string>(
	'Save Travel Rule SSI Passport'
	);

	const [ivms101, setIvms101] = useState<IIvms101Message>(emptyMessage);

	const handleFirstName = buildHandler(setFirstName);

	const handleLastName = buildHandler(setLastName);

	const handleStreetName = buildHandler(setStreetName);

	const handleBuildingNumber = buildHandler(setBuildingNumber);

	const handleCountry = (event: {
		target: { value: React.SetStateAction<string> };
		}): void => {
		setCountry(event.target.value);
	};

	return(
		<>
			<h4 className="major">Generate your Travel Rule SSI Passport </h4>
			<p style={{ width:'100%'}}>
				Create an <a href="https://intervasp.org/wp-content/uploads/2020/05/IVMS101-interVASP-data-model-standard-issue-1-FINAL.pdf">IVMS101 message</a> for KYC to make your digital identity compliant with the FATF Travel
				Rule to counteract money laundering and terrorism financing, and thus
				building a web of trust. This personal information will get encrypted by
				your SSI Travel Rule Key generated by your permawallet - only you decide
				who can read this message. You won&apos;t need to give this information
				anymore to third parties, over and over again. Your SSI Travel Rule -
				private - Key will get encrypted by your SSI Permawallet Key and saved
				into your wallet, so only you can access it. When making a transfer, you
				will have the option to attach this secret encrypted by the
				beneficiary&apos;s SSI Communication Key so they can read your Travel
				Rule Passport.
			</p>
			<form>
				<div className="fields">
				<div className="field half">
					<label>First name</label>
					<input type="text" onChange={handleFirstName} />
				</div>
				<div className="field half">
					<label>Last name</label>
					<input type="text" onChange={handleLastName} />
				</div>
				</div>
				
				<section style={{ width: '100%', marginBottom: '3%' }}>
				<h4>Residential address</h4>
				<div className="fields">
					<input
					type="text"
					placeholder="Street name"
					onChange={handleStreetName}
					/>
				</div>
				</section>
				<div className="fields">
				<div className="field half">
					<input
					type="text"
					placeholder="Building number"
					onChange={handleBuildingNumber}
					/>
				</div>
				<div className="field half">
					<select onChange={handleCountry}>
					<option value="">Select country of residence</option>
					<option value="Argentina">Argentina</option>
					<option value="Denmark">Denmark</option>
					<option value="Singapore">Singapore</option>
					<option value="United Kingdom">United Kingdom</option>
					</select>
				</div>
				</div>
				<ul className="actions">
				<li>
					<input
					type="button"
					className={passportButton}
					value={savePassport}
					onClick={() => {
						setIvms101({
						firstName,
						lastName,
						streetName,
						buildingNumber,
						country
						});
						setSavePassport('Saved');
						setPassportButton('button');
						dispatch(actionsCreator.setTravelRule(ivms101));
					}}
					/>
				</li>
				<li>
					<input
					type="reset"
					value="Reset"
					onClick={() => {
						setIvms101(emptyMessage);
						setSavePassport('Save SSI Travel Rule Passport');
						setPassportButton('button primary');
					}}
					/>
				</li>
				</ul>
			</form>
		</>
	);
};

export default TravelRule;
